### ISSUE TITLE
Crashes DF on Dwarf Naming

### ISSUE THREAD

**Issue by acwatkins** [splintermind/Dwarf-Therapist#230] opened 2014-12-29 17:10 UTC
DF 0.40.23
Latest DF2014 build
QT4
OSX

Outputs crazy characters on dwarf rename commit.  DF crashes after unpause.

**Comment by Hello71** [comment] 2014-12-29 17:17
Please run DT with `-debug` command line argument and pastebin the results.

**Comment by lethosor** [comment] 2014-12-29 18:41
Can you provide the ini file you're using?

**Comment by acwatkins** [comment] 2014-12-29 19:41
v0.40.23_osx.ini
http://pastebin.com/qFwL8e9i

**Comment by lethosor** [comment] 2014-12-29 20:02
@Hello71 it seems that running with "-debug" is not possible on OS X, as the flag only applies to the first (unauthorized) DT process.
At any rate, that layout appears to be correct.

**Comment by acwatkins** [comment] 2014-12-29 20:09
Didn't get anything special message from the crash.  I tried for a while on one session and it worked.  Next session (after restart,) I changed a labor, renamed, changed a labor, renamed and committed, then unpaused DF and DF crashed.

**Comment by fricy** [comment] 2014-12-29 20:33
After reading [this post](http://www.reddit.com/r/dwarffortress/comments/2prr2m/dwarf_therapist_issue/) I investigated a bit, and I can confirm that renaming can crash the game, but it's not consistent, it works most of the time, then crash... Applying new custom professions work perfectly, perhaps it's worth investigating what's the difference (if there's any) between the two string update methods.

[osx cust. prof. pr](https://github.com/splintermind/Dwarf-Therapist/pull/113)
[osx rename pr](https://github.com/splintermind/Dwarf-Therapist/pull/14)
-> I think that this commit was reverted later, but can't find it when/where.

Edit: [This should be it](https://github.com/splintermind/Dwarf-Therapist/issues/15)

**Comment by Hello71** [comment] 2014-12-29 23:02
Might be an issue with the DFInstanceNix string writing code in connection with OSX. I probably screwed up somewhere while moving it out of *OSX. I would suggest putting in some debug statements for the mapping and writing calls, since they seem to have been lost at some point.

**Comment by felliott** [comment] 2015-02-09 23:01
I think I have a fix for this, but I'm not much of a C++ programmer, so I just cargo-culted what I found in dfinstancelinux.cpp.  Please let me know if I should make any fixes.  Thank you!

Cheers,
Fitz

**Comment by fricy** [comment] 2015-03-02 17:59
[DT build with fix](https://www.dropbox.com/s/9n7evgwr8e9odfx/DwarfTherapist.31.0_experimental.dmg?dl=0)

**Comment by acwatkins** [comment] 2015-04-10 12:57
Tested fricy's build.  Seems to be fixed.  It now changes the names and hasn't crashed so far.

**Closed as completed** 2015-04-10 13:50 UTC
Labels: OSX, bug (major)
