### ISSUE TITLE
compiling without generating pdf?

### ISSUE THREAD

**Issue by SkaveRat** [splintermind/Dwarf-Therapist#186] opened 2014-09-17 02:44 UTC
Is there a way to not generate that pdf while building?

I'm not using it, and I'm really not going to install 700MB of latex+plugins on my machine to generate a pdf for DT

**Comment by splintermind** [comment] 2014-09-17 09:31
Duplicate of #183 which should be fixed with that merge.

**Closed as completed by splintermind** 2014-09-17 09:31 UTC
Labels: duplicate
